idf_component_register(
    SRCS
        "main.c"
        "app_orchestrator.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        app_config
        bt
        charger_state
        cuktech_ble
        cuktech_protocol
        esp_app_format
        esp_http_server
        esp_wifi
        json
        mbedtls
        mqtt
        mqtt_bridge
        nvs_flash
        web_config
        wifi_manager
)
