name: ESP-IDF build

on:
  push:
    branches:
      - main
      - "feat/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ESP32-C3 firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.2
          target: esp32c3
          path: .
          command: idf.py build
